--Graded Problems for Module 12
--Honors Assignment

--Q1
SELECT EVENTREQUEST.EVENTNO, CUSTNAME, PHONE,EVENTREQUEST.DATEAUTH
FROM EVENTREQUEST, CUSTOMER

WHERE EVENTREQUEST.CUSTNO = CUSTOMER.CUSTNO
AND
EVENTREQUEST.STATUS = 'Approved'
AND
EVENTREQUEST.EVENTNO NOT IN
(SELECT EVENTNO FROM EVENTPLAN)
;

--Q2
SELECT UNIQUE(EVENTREQUEST.EVENTNO), EVENTREQUEST.DATEREQ, EVENTREQUEST.DATEAUTH, EVENTPLAN.PLANNO,EVENTPLAN.WORKDATE, EMPLOYEE.EMPNAME
FROM 
EVENTREQUEST

INNER JOIN
EVENTPLAN ON EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
LEFT JOIN
EMPLOYEE ON EVENTPLAN.EMPNO = EMPLOYEE.EMPNO

WHERE
EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO

AND
EVENTREQUEST.DATEREQ BETWEEN '01-JUL-2022' AND '31-JUL-2022'
AND
EVENTREQUEST.DATEAUTH BETWEEN '01-JUL-2022' AND '31-JUL-2022'
AND
EVENTREQUEST.STATUS = 'Approved'

AND
EVENTPLAN.PLANNO IS NOT NULL
;

--Q3

SELECT PLANNO,WORKDATE,ACTIVITY,EMPNO,EMPNAME,DEPARTMENT, COUNT(LINENO) PLANLINE, COUNT(UNIQUE(RESNO)) AS U_RESR FROM 
(
SELECT EVENTPLAN.PLANNO, EVENTPLAN.WORKDATE, EVENTPLAN.ACTIVITY, EVENTPLAN.EMPNO, EMPNAME, DEPARTMENT, LINENO, RESNO
FROM
EVENTPLAN

LEFT JOIN 
EMPLOYEE ON EVENTPLAN.EMPNO = EMPLOYEE.EMPNO
INNER JOIN
EVENTPLANLINE ON EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO

WHERE EVENTPLAN.WORKDATE BETWEEN '01-Dec-2022' AND '31-Dec-2022'
)

GROUP BY PLANNO,WORKDATE,ACTIVITY,EMPNO,EMPNAME,DEPARTMENT
HAVING COUNT(UNIQUE(RESNO))>1
ORDER BY PLANNO;


--Q4

SELECT CUSTNO, CUSTNAME, CONTACT FROM CUSTOMER
WHERE CUSTNO NOT IN
(SELECT CUSTNO FROM EVENTREQUEST)
;


--Q5

SELECT EMPNO, EMPNAME, EMAIL_ID FROM EMPLOYEE
WHERE EMPNO NOT IN
(SELECT UNIQUE(EMPNO) FROM EVENTPLAN
WHERE WORKDATE BETWEEN '01-OCT-2022' AND '31-OCT-2022')
;


--Q6

SELECT EMPNAME, EMAIL_ID, AVG(Resource_Cost) FROM 
(
SELECT EMPNAME,EMAIL_ID,PLANNO, SUM(RESOURCECNT*RATE) AS Resource_Cost FROM
(
SELECT EVENTPLANLINE.PLANNO, EVENTPLANLINE.RESNO, EVENTPLANLINE.RESOURCECNT, RATE, EMPNAME, EMAIL_ID FROM EVENTPLANLINE

INNER JOIN
RESOURCETBL ON EVENTPLANLINE.RESNO = RESOURCETBL.RESNO
INNER JOIN
EVENTPLAN ON EVENTPLANLINE.PLANNO = EVENTPLAN.PLANNO
INNER JOIN 
EMPLOYEE ON EVENTPLAN.EMPNO = EMPLOYEE.EMPNO
)
GROUP BY EMPNAME,EMAIL_ID,PLANNO
)

GROUP BY EMPNAME,EMAIL_ID
;

--Q7

SELECT EVENTPLAN.PLANNO, EVENTPLAN.ACTIVITY, EVENTPLAN.WORKDATE FROM EVENTPLAN

INNER JOIN
EVENTPLANLINE ON EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
INNER JOIN
RESOURCETBL ON EVENTPLANLINE.RESNO = RESOURCETBL.RESNO

WHERE WORKDATE BETWEEN '01-DEC-2022' AND '31-DEC-2022'
AND
RATE >15;


INSERT INTO Facility ( FacNo, FacName )
VALUES ('F107', 'Swimming Pool');

INSERT INTO Location ( LocNo, FacNo, LocName )
VALUES ('L107', 'F107', 'Gate');

INSERT INTO Location ( LocNo, FacNo, LocName )
VALUES ('L108', 'F107', 'Locker Room');

UPDATE LOCATION SET LOCNAME ='Door' WHERE LOCNAME = ' swimming pool'
