Select distinct CITY , STATE, ZIP from CUSTOMER;

SELECT EMPNAME, PHONENO, EMAIL_ID from EMPLOYEE WHERE PHONENO LIKE '3-%';

SELECT * FROM RESOURCETBL WHERE Rate >=10 AND Rate<=20 order by RATE;

SELECT * FROM EVENTREQUEST WHERE (STATUS = 'Approved' or STATUS = 'Denied') AND (DATEAUTH >= '01-JUL-2022' AND DATEAUTH <= '31-JUL-2022');


SELECT LOCNO from LOCATION 
WHERE FACNO = 
(SELECT FACNO FROM FACILITY
WHERE FACNAME ='Basketball arena')
;

SELECT PLANNO, COUNT(LINENO) AS PLANLINE, SUM(resourcecnt) as RSRCNT FROM EVENTPLANLINE group by PLANNO;


SELECT PlanNO, COUNT(LINENO) as PlanLine, SUM(resourcecnt) as RSRCNT from EVENTPLANLINE 
WHERE 
TIMESTART BETWEEN  
TO_DATE('01-Oct-2022 00:00', 'DD-Mon-YYYY HH24:MI')
and
TO_DATE('31-Oct-2022 23:59', 'DD-Mon-YYYY HH24:MI')
Group  BY PlanNo
Having SUM(resourcecnt)>=10;
