--SELECT Statement Problems
--Q1
SELECT EventNo, Count(PlanNo) as Plans from EventPlan
WHERE EventNo IN 
(SELECT eventno FROM eventrequest)
Group By EventNo
Having Count(PlanNo) >1;

--Q2
SELECT PLANNO, EVENTNO, WORKDATE, ACTIVITY FROM
(
SELECT EVENTPLAN.PLANNO, EVENTPLAN.EVENTNO, EVENTPLAN.WORKDATE, EVENTPLAN.ACTIVITY, EVENTREQUEST.FACNO, FACILITY.FACNAME FROM EVENTPLAN

INNER JOIN
EVENTREQUEST ON EVENTPLAN.EVENTNO = EVENTRequest.EVENTNO

INNER JOIN
facility ON EVENTREQUEST.FACNO = facility.FACNO
)
WHERE FACNAME = 'Basketball arena' ;

--Q3
SELECT EVENTNO,DATEHELD,STATUS,ESTCOST FROM
(
SELECT EVENTREQUEST.EVENTNO, EVENTREQUEST.DATEHELD, EVENTREQUEST.STATUS, EVENTREQUEST.ESTCOST,FACNAME ,EMPNAME
FROM EVENTREQUEST

INNER JOIN
FACILITY ON EVENTREQUEST.FACNO = FACILITY.FACNO

INNER JOIN
EVENTPLAN ON EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO

INNER JOIN
EMPLOYEE ON EVENTPLAN.EMPNO = EMPLOYEE.EMPNO
)
WHERE (DATEHELD BETWEEN '01-OCT-2022' AND '31-DEC-2022')
AND
(EMPNAME = 'Mary Manager')
AND
(FACNAME = 'Basketball arena')
;

--Q4
SELECT 
PLANNO, LINENO, RESOURCECNT,TIMESTART,TIMEEND
FROM 
(
SELECT EVENTPLANLINE.PLANNO, EVENTPLANLINE.LINENO, EVENTPLANLINE.RESOURCECNT,
EVENTPLANLINE.TIMESTART,EVENTPLANLINE.TIMEEND, 
RESNAME, LOCNAME,FACNAME, ACTIVITY, WORKDATE
FROM 
EVENTPLANLINE

INNER JOIN 
RESOURCETBL ON EVENTPLANLINE.RESNO = RESOURCETBL.RESNO

INNER JOIN
LOCATION ON EVENTPLANLINE.LOCNO = LOCATION.LOCNO

INNER JOIN
FACILITY ON LOCATION.FACNO = FACILITY.FACNO

INNER JOIN 
EVENTPLAN ON EVENTPLANLINE.PLANNO = EVENTPLAN.PLANNO
)
WHERE FACNAME = 'Basketball arena'
AND
ACTIVITY ='Operation'
AND
(WORKDATE BETWEEN '01-OCT-2022' AND '31-DEC-2022')

;


--Q5
SELECT EVENTPLAN.PLANNO, SUM((EVENTPLANLINE.RESOURCECNT* RATE)) AS RESOURCE_COST 
FROM EVENTPLANLINE, EVENTPLAN, RESOURCETBL

WHERE EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
AND
EVENTPLANLINE.RESNO = RESOURCETBL.RESNO
AND
WORKDATE BETWEEN '01-DEC-2022' AND '31-DEC-2022'
GROUP BY EVENTPLAN.PLANNO
Having SUM((EVENTPLANLINE.RESOURCECNT* RATE))>50;


--Database Modification Problems
--Q1
INSERT INTO Facility (FACNO,FACNAME) VALUES ('F104','Swimming Pool');
--Q2
INSERT INTO LOCATION (LOCNO,FACNO,LOCNAME) VALUES ('L107','F104','Door');
--Q3
INSERT INTO LOCATION (LOCNO,FACNO,LOCNAME) VALUES ('L108','F104','Locker Room');
--Q4
UPDATE LOCATION SET LOCNAME = 'Gate' WHERE LOCNO ='L107';
--Q5
DELETE FROM LOCATION WHERE LOCNO IN ( 'L107', 'L108');


--SQL Statements with Errors and Poor Formatting

